test_plugin_info = {
	"license": "LGPL",
	"elements": [
		{
			"archetype": "GstBaseTransform",
			"classifications": [
				"Analyzer",
				"Audio"
			],
			"properties": [
				{
					"enumItems": [],
					"name": "Integration Window"
				}
			],
			"mediatype": "AUDIO",
			"name": "EBUR128 Analyzer",
			"description": "The EBUR128 Analyzer analyzes the Audio as it passes through and embeds Loudness-Events "
						   "into the Audio-Stream. These can later be visualized by the ebur128_display Element. If "
						   "all you want are the Loudness-Values, you can connect to the loudness-Signal of this "
						   "element. "
		},
		{
			"archetype": "GstBaseTransform",
			"classifications": [
				"Audio",
				"Visualisation"
			],
			"properties": [],
			"mediatype": "AUDIO",
			"name": "EBUR128 Display",
			"description": "Visualizes incoming Loudness-Values generated by the ebur128_analyzer Element. Generates a "
						   "Video-Stream from the Loudness-Events in the requested Format. "
		},
		{
			"archetype": "GstBaseTransform",
			"classifications": [
				"Filter",
				"Analyzer"
			],
			"properties": [
				{
					"enumItems": [],
					"name": "awsomeness",
					"description": "Sets the Awsomeness of this Filter between 0 and 1.",
					"type": "FLOAT"
				},
				{
					"enumItems": [],
					"name": "Amount of Love",
					"description": "Configures the Amount of Love this filter has between 0 and really huge.",
					"type": "UINT64"
				},
				{
					"enumItems": [
						"Red",
						"Green",
						"Blue",
						"Black"
					],
					"name": "Kind of Awsomeness",
					"description": "Selects the Kind of Awsomeness this filter applies.",
					"type": "ENUM"
				},
				{
					"enumItems": [],
					"name": "AwsomenessName",
					"description": "Name of the Awsomeness!",
					"type": "STRING"
				}
			],
			"mediatype": "VIDEO",
			"name": "Awsome Filter",
			"description": "This is a really awsome filter"
		}
	],
	"name": "EBUR 128 Loudness Meter",
	"description": "EBU R 128 is a guideline for loudness normalization and permitted maximum level of audio signals. "
				   "This Plugin adapts the great libav-filter to measure and visualize Loudness to GStreamer.",
	"author": "MaZderMind",
	"authorEmail": "peter@mazdermind.de",
	"url": "https://github.com/mazdermind/gst-ebur128-libav"
}
